apiVersion: v1
kind: Service
metadata:
  name: jquery
  namespace: k8s-jquery-svc
spec:
  selector: 
    app: jquery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
type: LoadBalancer